### PR TITLE
DampFloatList operator

### PR DESCRIPTION
**Pull request by alixcarolan**
Adapts the code from [Damp] into a new operator to work with float list inputs. Also adds more detailed documentation for the existing damping operators.

### CODE REVIEW

**Comment by ylmrx** [comment]
works for me ! gg :)

**Comment by pixtur** [comment]
Wait a sec. Why did you close this?

**Comment by alixcarolan** [comment]
Oh! I didn't mean to do that...

**Comment by pixtur** [comment]
Thanks for your contribution. I will try to clean it up a bit.

**Pull request merged**
